# Generated by Django 5.2.5 on 2026-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activity',
            name='object_type',
            field=models.CharField(default='file', max_length=16),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('view', 'View'), ('download', 'Download'), ('folder_create', 'Folder Create'), ('rename', 'Rename'), ('move', 'Move'), ('copy', 'Copy'), ('star', 'Star'), ('unstar', 'Unstar'), ('delete', 'Delete'), ('restore', 'Restore'), ('permanent_delete', 'Permanent Delete')], max_length=32),
        ),
    ]
