# Generated by Django 5.2.5 on 2026-08-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_metadata_activity_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('view', 'View'), ('download', 'Download'), ('folder_create', 'Folder Create'), ('rename', 'Rename'), ('move', 'Move'), ('copy', 'Copy'), ('star', 'Star'), ('unstar', 'Unstar'), ('delete', 'Delete'), ('restore', 'Restore'), ('permanent_delete', 'Permanent Delete'), ('share', 'Share'), ('unshare', 'Unshare'), ('permission_change', 'Permission Change'), ('link_create', 'Link Create'), ('link_update', 'Link Update'), ('link_disable', 'Link Disable'), ('link_regenerate', 'Link Regenerate'), ('public_access', 'Public Access'), ('public_download', 'Public Download')], max_length=32),
        ),
    ]
