# Generated by Django 5.2.5 on 2026-08-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, unique=True)),
                ('default_quota', models.PositiveBigIntegerField(default=10737418240)),
                ('max_upload_size', models.PositiveBigIntegerField(default=524288000)),
                ('max_file_versions', models.PositiveIntegerField(default=20)),
                ('trash_retention_days', models.PositiveIntegerField(default=30)),
                ('public_sharing_enabled', models.BooleanField(default=True)),
                ('max_public_link_days', models.PositiveIntegerField(default=90)),
                ('upload_requests_enabled', models.BooleanField(default=True)),
                ('max_request_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
