# Generated by Django 5.2.5 on 2026-08-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'permissions': [('access_administration', 'Can access application administration'), ('view_users', 'Can view user accounts'), ('manage_users', 'Can create, activate, and deactivate users'), ('manage_quotas', 'Can manage user storage quotas'), ('view_storage_analytics', 'Can view storage analytics'), ('view_file_analytics', 'Can view file analytics'), ('view_sharing_analytics', 'Can view sharing analytics'), ('view_audit_log', 'Can view the audit log'), ('manage_system_settings', 'Can manage system settings'), ('manage_roles', 'Can assign platform roles')], 'verbose_name_plural': 'system settings'},
        ),
    ]
