# Generated by Django 5.2.5 on 2026-08-19 08:24

import apps.sharing.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_favorite_file_files_file_owner_i_442223_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(db_index=True, default=apps.sharing.models.secure_token, editable=False, max_length=86, unique=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveBigIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_links', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='files.file')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='files.folder')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='sharing_sha_is_acti_d50881_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('folder__isnull', True)), models.Q(('file__isnull', True), ('folder__isnull', False)), _connector='OR'), name='link_exactly_one_item')],
            },
        ),
        migrations.CreateModel(
            name='SharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission', models.CharField(choices=[('viewer', 'Viewer'), ('downloader', 'Downloader'), ('editor', 'Editor')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_permissions', to='files.file')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_permissions', to='files.folder')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['shared_with', 'permission'], name='sharing_sha_shared__487c9e_idx'), models.Index(fields=['shared_by', 'created_at'], name='sharing_sha_shared__564141_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), ('folder__isnull', True)), models.Q(('file__isnull', True), ('folder__isnull', False)), _connector='OR'), name='share_exactly_one_item'), models.UniqueConstraint(fields=('shared_with', 'file'), name='unique_user_file_share'), models.UniqueConstraint(fields=('shared_with', 'folder'), name='unique_user_folder_share')],
            },
        ),
    ]
