# Generated by Django 5.2.5 on 2026-08-19 09:16

import apps.file_requests.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0003_file_current_version_number_fileversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(db_index=True, default=apps.file_requests.models.request_token, editable=False, max_length=86, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_count', models.PositiveIntegerField(default=0)),
                ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_requests', to=settings.AUTH_USER_MODEL)),
                ('destination_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_requests', to='files.folder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=160)),
                ('uploader_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_upload_metadata', to='files.file')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='file_requests.uploadrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='uploadrequest',
            index=models.Index(fields=['token', 'is_active', 'expires_at'], name='file_reques_token_56d5b6_idx'),
        ),
    ]
