# Generated by Django 5.2.5 on 2026-08-19 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_favorite_file_files_file_owner_i_442223_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='current_version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField()),
                ('storage_path', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=80, unique=True)),
                ('size', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.file')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['file', 'version_number'], name='files_filev_file_id_eeba2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('file', 'version_number'), name='unique_file_version_number')],
            },
        ),
    ]
